# Generated by Django 5.2 on 2025-06-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=255)),
                ('edad', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=20)),
                ('ingreso_mensual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_propiedad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ahorros', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
